import React from "react";

const Cuisines = () => {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "Right",
        alignItems: "Right",
        height: "100vh",
      }}>
      <h3>
        This menu can be a collection of recipes that are generated by users
        preferences, or recipes that are currently trending or popular. It can
        be a great way to introduce new users to the app and get them excited
        about the content.
      </h3>
    </div>
  );
};

export default Cuisines;
